version: '3.8'

services:
  nestjs-app:
    image: node:18
    container_name: products-api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mongodb://root:root@mongodb:27017
      - API_PORT=8080
    command: bash -c "npm i -g npm@latest && npm install --legacy-peer-deps && npm run build && npm run start:prod"
    depends_on:
      - mongodb
    networks:
      - intra

  mongodb:
    image: mongo:latest
    container_name: products_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - intra

networks:
  intra:
    driver: bridge
